### ISSUE TITLE
using <template> in tests, how to rerender with an updated parameter

### ISSUE THREAD

**Issue by cah-brian-gantzler** [ember-cli/ember-template-imports#189]
In tests, when using hbs, you can update a param with set, rerender and get the change.
given as TestComponent2
```hbs
<template>
  {{#if @param}}
    hello
  {{/if}}
</template>
```
you can do this test and it works. 
```js
  test('it renders hbs', async function (assert) {
    this.param = false;

    await render(hbs`<TestComponent2 @param={{this.param}}/>`);

    assert.dom(this.element).hasText('');

    set(this, "param", true);

    await rerender();   // can also use settled
    assert.dom(this.element).hasText('hello');
  });

```

Since the context is changed for gjs, the following test does not work. 
```js
  test('it renders gjs', async function (assert) {
    let param = false;

    await render(<template><TestComponent2 @param={{param}}/></template>);

    assert.dom(this.element).hasText('');

    param = true;

    await rerender();
    assert.dom(this.element).hasText('hello');
  });
```

Cant really use set or notifyPropertyChange as the param is not on an object to pass. One way I see is to create a class with param tracked but that seems overkill for tests from what we had before. 

What is the recommended way to write tests that update params when using `<template>` in tests?

**Comment by NullVoxPopuli** [comment]
Param isn't tracked -- this is what i do: 
https://github.com/universal-ember/ember-primitives/pull/79/files#diff-5531fdd2c3fe5e2ccff7b580876a323ff6e48bed73881d5e316dd19c184ed689R13

```js
test('with a value', async function (assert) {
    class State {
      @tracked value = 0;
    }

    let state = new State();

    await render(
      <template>
        <Progress @value={{state.value}} as |x|>
          <div id="value">{{x.value}}</div>
          <div id="percent">{{x.percent}}</div>
          <x.Indicator />
        </Progress>
      </template>
    );


```

You could also use cell, TrackedObject, etc

**Comment by NullVoxPopuli** [comment]
Allllso, you can replace

```js
assert.dom(this.element)
```

With

```js
assert.dom()
```

**Comment by cah-brian-gantzler** [comment]
> One way I see is to create a class with param tracked but that seems overkill for tests from what we had before.

Yes, I had suggested the class above. What should we be teaching as the recommended way? Guides prob needed updated to let people know. 

> Allllso, you can replace
> 
> ```js
> assert.dom(this.element)
> ```
> 
> With
> 
> ```js
> assert.dom()
> ```
> 
> `this` isn't needed in tests, and i kinda want to lint against it

This was just an example test and was generated from blueprints, so blueprints should be updated.

**Comment by NullVoxPopuli** [comment]
>  What should we be teaching as the recommended way? Guides prob needed updated to let people know.

yeah, the guides are still "Octane", and become less and less relevant as we move towards polaris -- the guides will need a big overhaul before we declare polaris released tho.

>  so blueprints should be updated.

yes

**Comment by NullVoxPopuli** [comment]
gonna close -- I think this is resolved

**Comment by cah-brian-gantzler** [comment]
Thanks, yes, should have closed. Have been doing what you suggested for a while now.
