### ISSUE TITLE
Yielding of advanced components

### ISSUE THREAD

**Issue by BwehaaFox** [ember-cli/ember-template-imports#240]
Adapting old components to the import mechanics, I was glad to note that the `component` helper works well with imports, but there were questions about typing

For context, the `BlockHTMLSignature` interface implements a shortcut for the standard signature structure, in fact `[{ icon: typeof Icon }]` is the default block definition.

If you try to pass the imported component directly to the block, there are no problems

```gjs
import Icon from './ui/icon';
export default class extends Component<BlockHTMLSignature<Args, [{ icon: typeof Icon }]>> {
  <template>
    {{yield (hash icon=Icon)}}
  </template>
}
```

But if necessary, set the default values ​​"as before", through the `component` helper:

```gjs
import Icon from './ui/icon';
export default class extends Component<BlockHTMLSignature<Args, [{ icon: typeof Icon }]>> {
  <template>
    {{#let (component Icon inline_shift=true)  as |ModIcon|}}
      {{yield (hash icon=ModIcon)}}
    {{/let}}
  </template>
}
```

A warning appears:
```
Type 'Invokable<(named?: PrebindArgs<{ inline_shift?: boolean; ... | ... 179 more ...  } & NamedArgsMarker,...' is not assignable to type 'typeof Icon'.
  Cannot assign an abstract constructor type to a non-abstract constructor type.glint(2322)
```

The question is: is there another specialized helper for such a situation, or is there an alternative new way of passing an extended component, or is it necessary to somehow modify the definition of `defaults: [{ icon: typeof Icon }]` for such cases with some existing interface or specific signature?

**Comment by NullVoxPopuli** [comment]
what's the type of `BlockHTMLSignature` ?

**Comment by BwehaaFox** [comment]
As I wrote above, just "shortcut"

```ts
declare interface HTMLSignature<T extends {} = {}> {
  Args: {
    [key in keyof T]: T[key]
  };
  Element: HTMLElement;
}

declare interface BlockHTMLSignature<J extends {} = {}, T extends Object | any[] = any[]> extends HTMLSignature<J> {
  Blocks: T extends any[] ? {
    default: T
  } : {
    [key in keyof T]: T[key]
  } 
}
```

**Comment by BwehaaFox** [comment]
Solution found [here](https://typed-ember.gitbook.io/glint/using-glint/glint-types)
As a result, there really is a special type `WithBoundArgs` to solve this problem

```gjs
import Icon from './ui/icon';
export default class extends Component<BlockHTMLSignature<Args, [{ icon: WithBoundArgs<typeof Icon, 'inline_shift'> }]>> {
  <template>
    {{#let (component Icon inline_shift=true)  as |ModIcon|}}
      {{yield (hash icon=ModIcon)}}
    {{/let}}
  </template>
}

```

This way the error disappears
