### ISSUE TITLE
Move this package into the ember-cli or emberjs GitHub org

### ISSUE THREAD

**Issue by steveszc** [ember-cli/ember-template-imports#250]
This package is core infrastructure/tooling for Ember's GTS/GJS format. 
As such, it ought not be owned by an org with a single member, but rather it ought to be owned by one of the official Ember GitHub orgs such as [ember-cli ](https://github.com/ember-cli or [emberjs](https://github.com/emberjs)

**Comment by SergeAstapov** [comment]
Looks like this was completed?
