### ISSUE TITLE
Invalid value type 'anyref' on ember 3.27

### ISSUE THREAD

**Issue by BwehaaFox** [ember-cli/ember-template-imports#272]
I'm trying to integrate this addon into an old working project running ember 3.27. Using Node 14.18.0, packages updated according to recommendations:

``` json
"ember-cli": "^3.27.0",
"ember-cli-typescript": "^5.2.1",
"@glint/core": "^1.5.0",
"@glint/environment-ember-loose": "^1.5.0",
"@glint/template": "^1.5.0",
"ember-cli-babel": "^8.2.0",
"ember-cli-htmlbars": "^6.3.0",
"ember-template-imports": "^4.2.0",
"ember-template-lint": "5.8.0",
"eslint-plugin-ember": "^11.6.0",
"prettier-plugin-ember-template-tag": "^2.0.4",
```

When I try to build the application, I get an error at the very start

```
WebAssembly.Module(): invalid value type 'anyref', enable with --experimental-wasm-anyref @+106

```

<details><summary>Stack Trace and Error Report</summary>
<p>

=================================================================================

ENV Summary:

  TIME: Sat Nov 30 2024 15:28:06 GMT+0300 (Москва, стандартное время)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\bweha\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - serve
  - --port
  - 4201
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: G:\Temp
  SHELL: null
  PATH:
  - C
  - \Program Files (x86)\VMware\VMware Workstation\bin\;H
  - \Oculus\Support\oculus-runtime;L
  - \Gradle\gradle-7.3.3\bin;C
  - \Users\bweha\AppData\Local\Android\Sdk;C
  - \Users\bweha\AppData\Local\Android\Sdk\platform-tools;C
  - \Users\bweha\AppData\Local\Android\Sdk\tools;C
  - \Users\bweha\AppData\Local\Android\Sdk\build-tools\32.0.0;C
  - \Users\bweha\AppData\Local\Android\Sdk\tools\emulator;C
  - \Users\bweha\.jdks\corretto-11.0.16.1\bin;L
  - \ImageMagick-6.9.9-Q16;C
  - \Program Files (x86)\Common Files\Oracle\Java\javapath;C
  - \Windows\system32;C
  - \Windows;C
  - \Windows\System32\Wbem;C
  - \Windows\System32\WindowsPowerShell\v1.0\;C
  - \Windows\System32\OpenSSH\;C
  - \Program Files\Git\cmd;C
  - \Program Files\dotnet\;C
  - \Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C
  - \Users\bweha\AppData\Roaming\nvm;C
  - \Program Files\nodejs;C
  - \Program Files (x86)\NVIDIA Corporation\PhysX\Common;G
  - \AndroidHome;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \WINDOWS\System32\OpenSSH\;;C
  - \Program Files\Docker\Docker\resources\bin;C
  - \Program Files\AmneziaWG\;C
  - \Users\bweha\AppData\Local\Programs\Python\Python310\Scripts\;C
  - \Users\bweha\AppData\Local\Programs\Python\Python310\;C
  - \Users\bweha\AppData\Local\Microsoft\WindowsApps;C
  - \Users\bweha\AppData\Local\Programs\Microsoft VS Code\bin;C
  - \Users\bweha\AppData\Roaming\npm
  PLATFORM: win32 x64
  FREEMEM: 9694011392
  TOTALMEM: 34175336448
  UPTIME: 147070
  LOADAVG: 0,0,0
  CPUS:
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  - 12th Gen Intel(R) Core(TM) i7-12700KF - 3610
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.2
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 8
  - nghttp2: 1.42.0
  - node: 14.18.0
  - openssl: 1.1.1l
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.42.0
  - v8: 8.4.371.23-node.84
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: WebAssembly.Module(): invalid value type 'anyref', enable with --experimental-wasm-anyref @+106
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: WebAssembly.Module(): invalid value type 'anyref', enable with --experimental-wasm-anyref @+106
  - name: CompileError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: CompileError: WebAssembly.Module(): invalid value type 'anyref', enable with --experimental-wasm-anyref @+106
    at Object.<anonymous> (L:\Web-Templates\ProLog\mr2-web-client\media-rights\node_modules\content-tag\pkg\node\content_tag.cjs:503:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (L:\Web-Templates\ProLog\mr2-web-client\media-rights\node_modules\content-tag\pkg\node.cjs:1:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

=================================================================================

</p>
</details> 

Did I update something wrong?

**Comment by NullVoxPopuli** [comment]
Node 14 doesn't effectively support wasm.
Any chance yau can upgrade node to 18 or higher?

If you really cannot upgrade node, you can downgrade a few dependencies, in exchange for receiving ~20 parsing bugs for gjs/gts
- ember-template-imports v3.*
- prettier-plugin-ember-template-tag v1.* (Not compatible with newest prettier)

**Comment by BwehaaFox** [comment]
Thanks for the tip. Is Node 14 an exception or do all new versions require Node > 18?
I looked at the description, and it says that > ​​12 is needed, which could possibly be misleading, or are there other pitfalls?

**Comment by NullVoxPopuli** [comment]
It's very likely that when we bumped ember-template-imports from v3 to v4, we forgot to update the node version in the README.

https://nodejs.org/en/about/previous-releases



The _engines_ for this package declare minimum Node 16: https://github.com/ember-cli/ember-template-imports/blob/master/package.json#L80

However, we're only running CI on node 18 -- so not testing node 16 may be a gap you've identified!


Latest v14 release was v14.21.3 on 2023-02-16 and was end-of-life'd on 2023-04-30 -- and node 12 was end-of-life'd on 2022-04-30 -- (end-of-life means no more security fixes -- generally about a year and a half after active development stops. If you can, upgrading node would be very beneficial <3

**Comment by BwehaaFox** [comment]
>  If you can, upgrading node would be very beneficial

I agree, but the problem is that I tried to avoid this, since the project is from Ember V1 with a lot of legacy code. Somehow it was raised to 3.27. Upgrading the Node version simply breaks everything without upgrading the Ember version, and switching to Ember V4+ is another adventure in this case. 

One way or another, this issue probably really needs to be resolved comprehensively, and gts seems to me to be a good reason for this

> may be a gap you've identified

I was glad to find it, I hope this issue will help newbies deal with this problem until the README is fixed

-------


A question out of curiosity, so as not to create a new issue: Technically, is it possible to import React addon modules into an Ember template via gts?

**Comment by NullVoxPopuli** [comment]
> Upgrading the Node version simply breaks everything without upgrading the Ember version

Let's debug it, then <3

Might be better to do so in discord.

> this issue will help newbies deal with this problem until the README is fixed

Would you like to open a PR?

> Technically, is it possible to import React addon modules into an Ember template via gts?

Yes. It's possible without gjs/gts as well.
You need a modifier or component manager, and you'd create a new react root at that initial boundary

**Comment by NullVoxPopuli** [comment]
Closing as the node in use is too old

**Comment by BwehaaFox** [comment]
> Let's debug it, then

I already took a radical path yesterday, since I already have experience migrating from v3 and upgraded to Node 18.20 and Ember 5.9. Now we are already at the stage of refactoring the business logic, there were no radical problems with the assembler. Anyway, thanks for the offer <3

> Would you like to open a PR?
I think it could, but since I have never done this in other people’s projects, I don’t really understand how to format it correctly. If anything happens, don’t scold too much...

> You need a modifier or component manager
Thanks for the tip, my last searches usually said that without an iframe this won't work in old templates, maybe something has changed

**Comment by NullVoxPopuli** [comment]
> don’t scold too much...

No worries <3 just want to give you credit

> maybe something has changed

With ember-source 3.25+ all _values_ cas be used in any syntax position, but with modifiers you can get around that a bit if you are on earlier versions of ember-source

**Comment by BwehaaFox** [comment]
Created PR https://github.com/ember-cli/ember-template-imports/pull/273

**Comment by NullVoxPopuli** [comment]
Thank you!!!
