### ISSUE TITLE
Prettier formater removes export default

### ISSUE THREAD

**Issue by BwehaaFox** [ember-cli/ember-template-imports#274]
I'm facing a problem with prettier formatting when used in gts files.

I'm using the explicit export format:

```gjs
import { TOC } from '@ember/component/template-only';

interface Args {
  ...
}

export default <template>
  {{#let this.some as |some|}}
     ...
  {{/let}}
</template> as TOC<Args>
```

Otherwise I get the following error:

```
Expected to find: 'component:some-component' within './components/some-component' but got 'undefined'. Did you forget to 'export default' within './components/some-component'?
```

The error disappears if you don't use ```as TOC<Args>```

```gjs
import { TOC } from '@ember/component/template-only';

<template>
  {{#let this.some as |some|}}
     ...
  {{/let}}
</template>
```

I don't mind exporting explicitly, but using only the `Ember.js Extension Pack` and `Glint` plugins in VSCode, Prettier deletes `export default` when saving, which prevents the use of formatting. Of course, you can export the template from a constant, but it seems unnecessary to me for such simple situations.

And actually I don't understand whether this is a problem in the Prettier configuration or is it intended (which adds non-obviousness when using). And is it a mistake to use `as TOC<Args>` without explicit export?

<details><summary>prettierrc.js</summary>
<p>

```js
 {
    singleQuote: true,
    'prettier/prettier': 'error',
    'arrow-body-style': 'off',
    'prefer-arrow-callback': 'off',
    parser: 'babel-ts',
    arrowParens: 'always',
    bracketSpacing: true,
    printWidth: 100,
    proseWrap: 'preserve',
    semi: true,
    tabWidth: 2,
    trailingComma: 'none',
    useTabs: false,
    endOfLine: 'auto',
    plugins: ['prettier-plugin-ember-template-tag'],
    overrides: [
      {
        files: '*.gjs',
        options: {
          parser: 'ember-template-tag'
        }
      },
  
      {
        files: '*.gts',
        options: {
          parser: 'ember-template-tag'
        }
      },
  
      {
        files: '*.hbs',
        options: {
          parser: 'glimmer'
        }
      }
    ]
  }
```

</p>
</details>

**Comment by NullVoxPopuli** [comment]
> I don't mind exporting explicitly, but using only the Ember.js Extension Pack and Glint plugins in VSCode, Prettier deletes export default when saving,

this is the intended behavior of prettier / template-tag-formatting

> which prevents the use of formatting

what do you mean? formatting still works?

>  Of course, you can export the template from a constant, but it seems unnecessary to me for such simple situations.

named exports are fantastic! in my most modern projects I have 0 default exports for components.


> And is it a mistake to use as TOC<Args> without explicit export?

you may want to do something like:

```glimmer-ts
<template>
  ...
</template> satisfies TOC<{ ... }>

// or

export const Foo = <template>
   ...
</template> satisfies TOC<{ ... }>
```

**Comment by BwehaaFox** [comment]
> which prevents the use of formatting

> what do you mean? formatting still works?

Possibly a translator problem. I meant that it complicates the use of automatic formatting since you have to return `export default` manually every time

> named exports are fantastic

I don’t argue, perhaps the habit of hbs templates speaks for me

> you may want to do something like

`satisfies` does prevent removal of `export default`, however using without `export default`:

```gjs
import { TOC } from '@ember/component/template-only';

interface Args {}

<template>
  some
</template> satisfies TOC<Args>;
```

Causes the same error

```
Expected to find: 'component:some-component' within './components/some-component' but got 'undefined'. Did you forget to 'export default' within './components/some-component'?
``` 

Is this correct behavior?

**Comment by NullVoxPopuli** [comment]
> Is this correct behavior?

maybe using `satisfies` is what tells prettier to not remove `export default`

**Comment by BwehaaFox** [comment]
Maybe. In general, if such use is not accidental, and it is correct

```gjs
import { TOC } from '@ember/component/template-only';

<template>
  some
</template> satisfies TOC;
```

then I think that we can close the question, since the main problem is solved <3
